import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  // Admin Modules
  {
    path: "",
    title: "ADMINISTRAVIMAS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },

  {
    path: "",
    title: "Skydelis",
    moduleName: "skydelis",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/administratorius/skydelis",
        title: "Administratorius",
        moduleName: "admin-skydelis",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/specialistas/skydelis",
        title: "Specialistas",
        moduleName: "specialistas-skydelis",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/seimininkas/skydelis",
        title: "Šeimininkas",
        moduleName: "seimininkas-skydelis",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "",
    title: "Valdymas",
    moduleName: "valdymas",
    iconType: "material-icons-two-tone",
    icon: "build",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/administratorius/paslaugos",
        title: "Paslaugos",
        moduleName: "paslaugos",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/administratorius/rusys",
        title: "Rūšys",
        moduleName: "rusys",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/administratorius/darbuotojai",
    title: "Darbuotojai",
    moduleName: "darbuotojas",
    iconType: "material-icons-two-tone",
    icon: "people",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "",
    title: "Specialistas",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "/specialistas/kalendorius",
    title: "Kalendorius",
    moduleName: "kalendorius",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "",
    title: "Rezervacija",
    moduleName: "reservations",
    iconType: "material-icons-two-tone",
    icon: "assignment",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/specialistas/rezervacija-priemimas",
        title: "Rezervacijų priėmimas",
        moduleName: "rezervacija-priemimas",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/specialistas/rezervacija-perziura",
        title: "Rezervacijų peržiūra",
        moduleName: "vizitas-rezervacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/specialistas/konsultacija",
    title: "Pagalba",
    moduleName: "konsultacijaa",
    iconType: "material-icons-two-tone",
    icon: "email",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "",
    title: "PAGRINDINIS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "/seimininkas/gyvunai",
    title: "Gyvūnas",
    moduleName: "animals",
    iconType: "material-icons-two-tone",
    icon: "local_hospital",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  {
    path: "",
    title: "Vizitas",
    moduleName: "visits",
    iconType: "material-icons-two-tone",
    icon: "widgets",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [
      {
        path: "/seimininkas/vizitai-istorija",
        title: "Vizitų istorija",
        moduleName: "vizitas-istorija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/seimininkas/vizitai-rezervacija",
        title: "Vizito rezervacija",
        moduleName: "vizitas-rezervacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/seimininkas/konsultacija",
    title: "Konsultacija",
    moduleName: "konsultacija",
    iconType: "material-icons-two-tone",
    icon: "chat",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["ADMIN"],
    submenu: [],
  },
  // Doctor Modules
  {
    path: "",
    title: "Specialistas",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  {
    path: "",
    title: "Skydelis",
    moduleName: "skydelis",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [
      {
        path: "/specialistas/skydelis",
        title: "Specialistas",
        moduleName: "specialistas-skydelis",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/seimininkas/skydelis",
        title: "Šeimininkas",
        moduleName: "seimininkas-skydelis",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/specialistas/kalendorius",
    title: "Kalendorius",
    moduleName: "kalendorius",
    iconType: "material-icons-two-tone",
    icon: "event_note",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  {
    path: "",
    title: "Rezervacija",
    moduleName: "reservations",
    iconType: "material-icons-two-tone",
    icon: "assignment",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [
      {
        path: "/specialistas/rezervacija-priemimas",
        title: "Rezervacijų priėmimas",
        moduleName: "rezervacija-priemimas",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/specialistas/rezervacija-perziura",
        title: "Rezervacijų peržiūra",
        moduleName: "vizitas-rezervacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/specialistas/konsultacija",
    title: "Pagalba",
    moduleName: "konsultacijaa",
    iconType: "material-icons-two-tone",
    icon: "email",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  {
    path: "",
    title: "PAGRINDINIS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  {
    path: "/seimininkas/gyvunai",
    title: "Gyvūnas",
    moduleName: "animals",
    iconType: "material-icons-two-tone",
    icon: "local_hospital",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  {
    path: "",
    title: "Vizitas",
    moduleName: "visits",
    iconType: "material-icons-two-tone",
    icon: "widgets",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [
      {
        path: "/seimininkas/vizitai-istorija",
        title: "Vizitų istorija",
        moduleName: "vizitas-istorija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/seimininkas/vizitai-rezervacija",
        title: "Vizito rezervacija",
        moduleName: "vizitas-rezervacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/seimininkas/konsultacija",
    title: "Konsultacija",
    moduleName: "konsultacija",
    iconType: "material-icons-two-tone",
    icon: "chat",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["MODERATOR"],
    submenu: [],
  },
  // Patient Modules
  {
    path: "",
    title: "PAGRINDINIS",
    moduleName: "",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["USER"],
    submenu: [],
  },
  {
    path: "/seimininkas/skydelis",
    title: "Skydelis",
    moduleName: "skydelis",
    iconType: "material-icons-two-tone",
    icon: "home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["USER"],
    submenu: [],
  },
  {
    path: "/seimininkas/gyvunai",
    title: "Gyvūnas",
    moduleName: "animals",
    iconType: "material-icons-two-tone",
    icon: "local_hospital",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["USER"],
    submenu: [],
  },
  {
    path: "",
    title: "Vizitas",
    moduleName: "visits",
    iconType: "material-icons-two-tone",
    icon: "widgets",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["USER"],
    submenu: [
      {
        path: "/seimininkas/vizitai-istorija",
        title: "Vizitų istorija",
        moduleName: "vizitas-istorija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/seimininkas/vizitai-rezervacija",
        title: "Vizito rezervacija",
        moduleName: "vizitas-rezervacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },
  {
    path: "/seimininkas/konsultacija",
    title: "Konsultacija",
    moduleName: "konsultacija",
    iconType: "material-icons-two-tone",
    icon: "chat",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["USER"],
    submenu: [],
  },
  // Common Modules
  //Nustatymu linkas, informacijos ir panasiai,
  /*{
    path: "/autentifikacija/prisijungimas",
    title: "Atsijungti",
    moduleName: "logout",
    iconType: "material-icons-two-tone",
    icon: "power_settings_new",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },*/
  /*{
    path: "",
    title: "Autentifikacija",
    moduleName: "autentifikacija",
    iconType: "material-icons-two-tone",
    icon: "supervised_user_circle",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/autentifikacija/prisijungimas",
        title: "Prisijungti",
        moduleName: "autentifikacija",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },*/
];
